// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: stream.proto

package protoImport

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StreamReqData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StreamReqData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StreamReqData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StreamReqDataMultiError, or
// nil if none found.
func (m *StreamReqData) ValidateAll() error {
	return m.validate(true)
}

func (m *StreamReqData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Data

	if len(errors) > 0 {
		return StreamReqDataMultiError(errors)
	}

	return nil
}

// StreamReqDataMultiError is an error wrapping multiple validation errors
// returned by StreamReqData.ValidateAll() if the designated constraints
// aren't met.
type StreamReqDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StreamReqDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StreamReqDataMultiError) AllErrors() []error { return m }

// StreamReqDataValidationError is the validation error returned by
// StreamReqData.Validate if the designated constraints aren't met.
type StreamReqDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StreamReqDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StreamReqDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StreamReqDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StreamReqDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StreamReqDataValidationError) ErrorName() string { return "StreamReqDataValidationError" }

// Error satisfies the builtin error interface
func (e StreamReqDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStreamReqData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StreamReqDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StreamReqDataValidationError{}

// Validate checks the field values on StreamRspData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StreamRspData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StreamRspData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StreamRspDataMultiError, or
// nil if none found.
func (m *StreamRspData) ValidateAll() error {
	return m.validate(true)
}

func (m *StreamRspData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Data

	if len(errors) > 0 {
		return StreamRspDataMultiError(errors)
	}

	return nil
}

// StreamRspDataMultiError is an error wrapping multiple validation errors
// returned by StreamRspData.ValidateAll() if the designated constraints
// aren't met.
type StreamRspDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StreamRspDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StreamRspDataMultiError) AllErrors() []error { return m }

// StreamRspDataValidationError is the validation error returned by
// StreamRspData.Validate if the designated constraints aren't met.
type StreamRspDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StreamRspDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StreamRspDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StreamRspDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StreamRspDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StreamRspDataValidationError) ErrorName() string { return "StreamRspDataValidationError" }

// Error satisfies the builtin error interface
func (e StreamRspDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStreamRspData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StreamRspDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StreamRspDataValidationError{}
